[package]
name = "pog"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_12"] }
memmap2 = "0.9"
clap = { version = "4", features = ["derive"] }
async-channel = "2.0"

[profile.release]
opt-level = 3
lto = true
